-- MySQL Script generated by MySQL Workbench
-- Tue Feb 20 19:39:58 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema banco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco` DEFAULT CHARACTER SET utf8 ;
USE `banco` ;

-- -----------------------------------------------------
-- Table `banco`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`cliente` (
  `rut` VARCHAR(12) NOT NULL,
  `nombre` VARCHAR(75) NOT NULL,
  `apellidos` VARCHAR(75) NOT NULL,
  `sexo` TINYINT(1) NOT NULL,
  `fecha_nacimiento` DATETIME NULL,
  PRIMARY KEY (`rut`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`cuenta` (
  `nro_cuenta` INT NOT NULL,
  `rut` VARCHAR(12) NOT NULL,
  `saldo` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`nro_cuenta`),
  UNIQUE INDEX `nro_cuenta_UNIQUE` (`nro_cuenta` ASC),
  INDEX `fk_cuenta_cliente_idx` (`rut` ASC),
  CONSTRAINT `fk_cuenta_cliente`
    FOREIGN KEY (`rut`)
    REFERENCES `banco`.`cliente` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`movimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`movimiento` (
  `id_movimiento` INT NOT NULL AUTO_INCREMENT,
  `nro_cuenta` INT NOT NULL,
  `tipo_movimiento` VARCHAR(10) NOT NULL,
  `saldo_anterior` DECIMAL(12,2) NULL,
  `monto` DECIMAL(12,2) NOT NULL,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_movimiento`),
  INDEX `fk_movimiento_cuenta_idx` (`nro_cuenta` ASC),
  CONSTRAINT `fk_movimiento_cuenta`
    FOREIGN KEY (`nro_cuenta`)
    REFERENCES `banco`.`cuenta` (`nro_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `banco`;

DELIMITER $$
USE `banco`$$
CREATE DEFINER = CURRENT_USER TRIGGER `banco`.`movimiento_AFTER_INSERT` AFTER INSERT ON `movimiento` FOR EACH ROW
BEGIN

	IF (NEW.tipo_movimiento = 'egreso') THEN
		update cuenta set cuenta.saldo = cuenta.saldo - NEW.monto 
		WHERE cuenta.nro_cuenta = NEW.nro_cuenta;
	ELSEIF (NEW.tipo_movimiento = 'ingreso') THEN
		update cuenta set cuenta.saldo = cuenta.saldo + NEW.monto 
		WHERE cuenta.nro_cuenta = NEW.nro_cuenta;
	END IF;
END$$

USE `banco`$$
CREATE DEFINER = CURRENT_USER TRIGGER `banco`.`movimiento_BEFORE_INSERT` BEFORE INSERT ON `movimiento` FOR EACH ROW
BEGIN
	IF NEW.saldo_anterior IS NULL THEN
		SET NEW.saldo_anterior = (SELECT cuenta.saldo FROM cuenta WHERE cuenta.nro_cuenta = NEW.nro_cuenta);
	END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
